import { coreColors } from './core';

export const colors = {
  theme: {
    light: {
      border: {
        minimal: coreColors.gray10,
        subtle: coreColors.gray20,
        moderate: coreColors.gray40,
        accent: coreColors.blue20,
        bold: coreColors.blue40,
        selected: coreColors.orange30,
        contrast: coreColors.black,
        reversed: coreColors.white,
        error: coreColors.red30,
        success: coreColors.green40,
        warning: coreColors.yellow50,
        info: coreColors.blue50,
        disabled: coreColors.gray20,
      },
      surface: {
        background: coreColors.white,
        primary: coreColors.white,
        secondary: coreColors.gray10,
        tertiary: coreColors.gray40,
        quaternary: coreColors.gray50,
        contrast: coreColors.black,
        bold: coreColors.blue30,
        selected: coreColors.orange30,
        subtle: coreColors.blue10,
        accent: coreColors.orange10,
        message: coreColors.orange10,
        indicator: coreColors.green20,
        highlight: coreColors.orange30,
        disabled: coreColors.gray10,
        error: coreColors.red10,
        success: coreColors.green10,
        warning: coreColors.yellow10,
        info: coreColors.blue10,
        on: coreColors.green20,
      },
      text: {
        primary: coreColors.black,
        secondary: coreColors.gray65,
        tertiary: coreColors.gray50,
        quaternary: coreColors.gray40,
        title: coreColors.orange40,
        heading: coreColors.blue40,
        link: coreColors.blue40,
        button: coreColors.white,
        control: coreColors.gray20,
        error: coreColors.red30,
        success: coreColors.green40,
        warning: coreColors.yellow50,
        info: coreColors.blue50,
        accent: coreColors.blue30,
        highlight: coreColors.orange30,
        bold: coreColors.black,
        disabled: coreColors.gray40,
        reversed: coreColors.white,
      },
      status: {
        info: coreColors.blue40,
        warning: coreColors.yellow30,
        error: coreColors.red30,
        success: coreColors.green10,
      },
      gradient: {
        blue10: `linear-gradient(50.19deg, ${coreColors.blue30} 2.84%, #0367b2 106.82%)`,
        orange10: `linear-gradient(43.07deg, ${coreColors.orange40} -3.02%, ${coreColors.orange30} 93.96%)`,
        orange20: `linear-gradient(225.88deg, ${coreColors.orange40} 7.79%, ${coreColors.orange50} 104.6%);
          `,
      },
    },
    dark: {
      border: {
        minimal: coreColors.gray65,
        subtle: coreColors.gray55,
        moderate: coreColors.gray45,
        accent: coreColors.blue35,
        bold: coreColors.blue35,
        selected: coreColors.orange20,
        contrast: coreColors.orange10,
        reversed: coreColors.gray50,
        error: coreColors.red20,
        success: coreColors.green30,
        warning: coreColors.yellow50,
        info: coreColors.blue50,
        disabled: coreColors.gray55,
      },
      surface: {
        background: coreColors.gray70,
        primary: coreColors.gray60,
        secondary: coreColors.gray55,
        tertiary: coreColors.gray45,
        quaternary: coreColors.gray30,
        contrast: coreColors.white,
        bold: coreColors.blue30,
        selected: coreColors.orange30,
        accent: coreColors.orange50,
        subtle: coreColors.orange10,
        message: coreColors.brown10,
        indicator: coreColors.green35,
        highlight: coreColors.orange25,
        disabled: coreColors.gray65,
        error: coreColors.red40,
        success: coreColors.green40,
        warning: coreColors.yellow10,
        info: coreColors.blue50,
        on: coreColors.green40,
      },
      text: {
        primary: coreColors.white,
        secondary: coreColors.gray10,
        tertiary: coreColors.gray20,
        quaternary: coreColors.gray30,
        title: coreColors.orange25,
        heading: coreColors.blue35,
        link: coreColors.blue20,
        button: coreColors.white,
        control: coreColors.gray55,
        error: coreColors.red20,
        success: coreColors.green30,
        warning: coreColors.yellow50,
        info: coreColors.blue50,
        accent: coreColors.green30,
        highlight: coreColors.orange25,
        bold: coreColors.white,
        disabled: coreColors.gray45,
        reversed: coreColors.black,
      },
      status: {
        info: coreColors.blue30,
        warning: coreColors.orange25,
        error: coreColors.red20,
        success: coreColors.green35,
      },
      gradient: {
        blue10: `linear-gradient(50.19deg, ${coreColors.blue30} 2.84%, #0367b2 106.82%)`,
        orange10: `linear-gradient(43.07deg, ${coreColors.orange40} -3.02%, ${coreColors.orange30} 93.96%)`,
        orange20: `linear-gradient(225.88deg, ${coreColors.orange40} 7.79%, ${coreColors.orange50} 104.6%);
          `,
      },
    },
  },
};
