import { coreColors } from "./core";

export const colors = {
    theme: {
      light: {
        border: {
          minimal: coreColors.gray10,
          subtle: coreColors.gray20,
          moderate: coreColors.gray30,
          accent: coreColors.blue20,
          bold: coreColors.blue40,
          selected: coreColors.orange30,
          contrast: coreColors.black,
          reversed: coreColors.white,
          error: coreColors.red20,
          success: coreColors.green40,
          disabled: coreColors.gray20,
        },
        surface: {
          background: coreColors.white,
          primary: coreColors.white,
          secondary: coreColors.gray10,
          tertiary: coreColors.gray50,
          contrast: coreColors.black,
          bold: coreColors.blue30,
          selected: coreColors.orange30,
          subtle: coreColors.blue10,
          accent: coreColors.orange10,
          message: coreColors.orange10,
          indicator: coreColors.green20,
          highlight: coreColors.orange30,
          disabled: coreColors.gray10,
          error: coreColors.red10,
          success: coreColors.green10,
          on: coreColors.green20,
        },
        text: {
          primary: coreColors.black,
          secondary: coreColors.gray40,
          tertiary: coreColors.gray30,
          quaternary: coreColors.gray60,
          title: coreColors.orange40,
          heading: coreColors.blue40,
          link: coreColors.blue40,
          button: coreColors.white,
          control: coreColors.gray20,
          error: coreColors.red20,
          success: coreColors.green40,
          accent: coreColors.blue30,
          highlight: coreColors.orange30,
          bold: coreColors.black,
          disabled: coreColors.gray30,
          reversed: coreColors.white,
        },
        status: {
          info: coreColors.blue40,
          warning: coreColors.orange30,
          error: coreColors.red20,
          success: coreColors.green10,
        },
        gradient: {
          blue10: `linear-gradient(50.19deg, ${coreColors.blue30} 2.84%, #0367b2 106.82%)`,
          orange10: `linear-gradient(43.07deg, ${coreColors.orange40} -3.02%, ${coreColors.orange30} 93.96%)`,
          orange20: `linear-gradient(225.88deg, ${coreColors.orange40} 7.79%, ${coreColors.orange50} 104.6%);
          `,
        },
      },
      dark: {
        border: {
          minimal: "#2D2E30",
          subtle: "#404040",
          moderate: "#6D6D6D",
          accent: "#3381CE",
          bold: "#3381CE",
          selected: "#FFB652",
          contrast: "#FFFFFF",
          reversed: "#000000",
          error: "#E04D4D",
          success: "#6BD36B",
          disabled: "#404040",
        },
        surface: {
          background: "#1A1B1D",
          primary: "#1A1B1D",
          secondary: "#2D2E30",
          tertiary: "#40404080",
          contrast: "#FFFFFF",
          bold: "#1E7ABC",
          selected: coreColors.orange30,
          accent: coreColors.orange10,
          subtle: coreColors.blue10,
          message: "#3E2D20",
          indicator: "#5C9E5E",
          highlight: "#FFB652",
          disabled: "#2D2E30",
          error: "#4A191B",
          success: "#264D37",
          on: "#264D37",
        },
        text: {
          primary: "#FFFFFF",
          secondary: "#B0B1B2",
          tertiary: "#6D6D6D",
          quaternary: "#FFB652",
          title: "#FFB652",
          heading: "#3381CE",
          link: "#3381CE",
          button: "#1A1B1D",
          control: "#404040",
          error: "#E04D4D",
          success: "#6BD36B",
          accent: "#6BD36B",
          highlight: "#FFB652",
          bold: "#FFFFFF",
          disabled: "#6D6D6D",
          reversed: "#000000",
        },
        status: {
          info: "#1E7ABC",
          warning: "#FFB652",
          error: "#E04D4D",
          success: "#5C9E5E",
        },
        gradient: {
          blue10: `linear-gradient(50.19deg, ${coreColors.blue30} 2.84%, #0367b2 106.82%)`,
          orange10: `linear-gradient(43.07deg, ${coreColors.orange40} -3.02%, ${coreColors.orange30} 93.96%)`,
          orange20: `linear-gradient(225.88deg, ${coreColors.orange40} 7.79%, ${coreColors.orange50} 104.6%);
          `,
        },
      },
    },
  }